CREATE TABLE answers (
  jmsid varchar(32),
  a1 text NOT NULL default '',
  a2 text NOT NULL default '',
  a3 text NOT NULL default '',
  a4 text NOT NULL default '',
  a5 text NOT NULL default '',
  a6 text NOT NULL default '',
  a7 text NOT NULL default '',
  a8 text NOT NULL default '',
  a9 text NOT NULL default '',
  a10 text NOT NULL default '',
  a11 text NOT NULL default '',
  a12 text NOT NULL default '',
  a13 text NOT NULL default '',
  a14 text NOT NULL default '',
  a15 text NOT NULL default '',
  a16 text NOT NULL default '',
  a17 text NOT NULL default '',
  a18 text NOT NULL default '',
  a19 text NOT NULL default '',
  a20 text NOT NULL default '',
  a21 text NOT NULL default '',
  a22 text NOT NULL default '',
  a23 text NOT NULL default '',
  a24 text NOT NULL default '',
  a25 text NOT NULL default '',
  a26 text NOT NULL default '',
  a27 text NOT NULL default '',
  a28 text NOT NULL default '',
  a29 text NOT NULL default '',
  a30 text NOT NULL default ''
);
