INSERT INTO questions (qnum, qtext) VALUES (1, 'I am very proud of');
INSERT INTO questions (qnum, qtext) VALUES (2, 'Managing people');
INSERT INTO questions (qnum, qtext) VALUES (3, 'The toughest part of managing people is');
INSERT INTO questions (qnum, qtext) VALUES (4, 'I am most creative');
INSERT INTO questions (qnum, qtext) VALUES (5, 'My hardest career decision has been');
INSERT INTO questions (qnum, qtext) VALUES (6, 'The most significant career event in my life was');
INSERT INTO questions (qnum, qtext) VALUES (7, 'When others get in my way I');
INSERT INTO questions (qnum, qtext) VALUES (8, 'I am most effective when');
INSERT INTO questions (qnum, qtext) VALUES (9, 'I am least effective when');
INSERT INTO questions (qnum, qtext) VALUES (10, 'My uniqueness is');
INSERT INTO questions (qnum, qtext) VALUES (11, 'In an organization, politically I');
INSERT INTO questions (qnum, qtext) VALUES (12, 'The kind of feedback I get');
INSERT INTO questions (qnum, qtext) VALUES (13, 'When embarking on a new venture I');
INSERT INTO questions (qnum, qtext) VALUES (14, 'My co-workers would describe me as');
INSERT INTO questions (qnum, qtext) VALUES (15, 'The most significant obstacle which frustrates my career/professional growth');
INSERT INTO questions (qnum, qtext) VALUES (16, 'I feel good about');
INSERT INTO questions (qnum, qtext) VALUES (17, 'What I might do differently is');
INSERT INTO questions (qnum, qtext) VALUES (18, 'Typically, when angry I');
INSERT INTO questions (qnum, qtext) VALUES (19, 'What I like most about myself is');
INSERT INTO questions (qnum, qtext) VALUES (20, 'What I like least about myself is');
INSERT INTO questions (qnum, qtext) VALUES (21, 'A good example of my common sense (“street smarts”) is');
INSERT INTO questions (qnum, qtext) VALUES (22, 'The most important lesson I have learned in life is');
INSERT INTO questions (qnum, qtext) VALUES (23, 'Security is');
INSERT INTO questions (qnum, qtext) VALUES (24, 'I usually handle disappointment and loss');
INSERT INTO questions (qnum, qtext) VALUES (25, 'My boss would describe me as');
INSERT INTO questions (qnum, qtext) VALUES (26, 'If I could start my career over again at my company, one thing I would definitely do is');
INSERT INTO questions (qnum, qtext) VALUES (27, 'If I could start my career over again at my company, one thing I would avoid doing is');
INSERT INTO questions (qnum, qtext) VALUES (28, 'Following through on a task');
INSERT INTO questions (qnum, qtext) VALUES (29, 'Handling “the boss” is');
INSERT INTO questions (qnum, qtext) VALUES (30, 'The difference between perception and reality is');
